using System.Collections.Generic;

namespace AirlockClient.Managers
{
    public static class ListsManager
    {
        public static List<(int id, string name)> hats = new()
        {
            (12, "No Hat"),
            (13, "Balloon"),
            (14, "Beanie"),
            (15, "FedoraTrillby"),
            (16, "FloatyFlamingo"),
            (17, "Greh"),
            (19, "Mohawk"),
            (20, "Sprout"),
            (21, "Batbean"),
            (22, "Headphones"),
            (23, "MiniCrewmate"),
            (24, "PlagueMask"),
            (25, "Present"),
            (26, "Candycane"),
            (27, "Decorations"),
            (28, "Elf"),
            (29, "Reindeer"),
            (30, "Santa"),
            (31, "Snowman"),
            (32, "Trophy"),
            (33, "Pizzatime"),
            (34, "Banana"),
            (35, "MagicCorn"),
            (36, "Morawk"),
            (37, "Note2Self"),
            (38, "ThirdEye"),
            (39, "Clogged"),
            (40, "ColdBrim"),
            (41, "LavaRock"),
            (42, "MinersSetback"),
            (43, "OSHACompliant"),
            (44, "PHat"),
            (45, "SafetySecond"),
            (46, "Snowmate"),
            (47, "ThisIsNotADrill"),
            (48, "UniqueSpecimen"),
            (49, "Crewhorse"),
            (50, "BearHug"),
            (51, "GasMask"),
            (52, "PengYinz"),
            (53, "SnowDay"),
            (54, "SnowflakeCrown"),
            (55, "CozyHat"),
            (56, "CozyMuffs"),
            (57, "IceCrewmate"),
            (58, "KittyHoodie"),
            (59, "WhippedCream"),
            (60, "Floatyasaurus"),
            (61, "Hooked"),
            (62, "CrabGrab"),
            (63, "Sandcastle"),
            (64, "Funguy"),
            (65, "BeanusFlytrap"),
            (66, "CapCap"),
            (67, "DishJockey"),
            (68, "MoRocks"),
            (69, "Sandmate"),
            (70, "ShadyBusiness"),
            (71, "Overscoped"),
            (72, "Zomburrito"),
            (73, "Chef"),
            (74, "VigilanteHat"),
            (75, "ContainmentHat"),
            (76, "Janitor"),
            (77, "MopHead"),
            (78, "ChocolateScoop"),
            (79, "LastWipe"),
            (80, "VictoriaHair"),
            (81, "WerewolfHat"),
            (82, "Pumpkin"),
            (83, "Wizard"),
            (84, "TenGallons_Stache"),
            (85, "TenGallons_White"),
            (86, "CashHat"),
            (87, "ChaosContainmentHat"),
            (88, "HazmatMask"),
            (89, "ScientistGoggles"),
            (90, "TopHatDark"),
            (91, "TopHatWhite"),
            (92, "FrogHat"),
            (93, "RedDragonHat"),
            (94, "RabbitEars"),
            (95, "PinkBow"),
            (96, "MooseHat"),
            (97, "LunarNewYearDragon"),
            (99, "AstronaughtHat"),
            (100, "PilotHat"),
            (101, "LunarNewYearDog"),
            (102, "NyanCatEars"),
            (103, "SidekickHat"),
            (104, "ScanalyzerHat"),
            (105, "ScanalyzerDeluxeHat"),
            (106, "SquidHat"),
            (107, "GreenFishHat"),
            (108, "MinerHatBrown"),
            (109, "TurtleHat"),
            (110, "HatVR_Black"),
            (111, "FrankenBeanHat"),
            (112, "SlimeHat"),
            (113, "ChopChop"),
            (114, "GreatGoalieHat"),
            (115, "ImpRessiveHat"),
            (116, "InnocenceHat"),
            (117, "PropellerHat"),
            (118, "BaubleTopper"),
            (119, "CoolSlopes"),
            (120, "CozyPuff"),
            (121, "FauxFurHoodie"),
            (122, "NewYears2026"),
            (123, "FOnesieHat"),
            (124, "SealHat"),
            (125, "TrainConductorHat"),
            (126, "WinterHat"),
            (207, "Pioneer"),
            (208, "TopHat"),
            (209, "Eggscellent"),
            (210, "GogglesUp"),
            (211, "LuvU"),
            (212, "Planted"),
            (213, "Lucky"),
            (214, "MysteriousVagabond"),
            (215, "DaisyMeRollin"),
            (216, "IceCrown"),
            (217, "3dGlasses"),
            (218, "StormCloudHat"),
            (219, "FoxEars"),
            (220, "GreyFoxEars"),
            (221, "BlueDog"),
            (222, "PoorReception"),
            (223, "Viking"),
            (224, "BullHeaded"),
            (225, "ZodiacChicken"),
            (226, "TheGoat"),
            (227, "ZodiacHorse"),
            (228, "ImAllEars"),
            (229, "Pig"),
            (230, "MouseEars"),
            (231, "TigerEars"),
            (232, "Toaster"),
            (233, "BunnyEars"),
            (234, "CatEars"),
            (235, "BuffaloHorn"),
            (236, "EagleBeak"),
            (237, "RaccoonHat"),
            (238, "LunarNewYear_Snake"),
            (239, "MouseHat"),
            (240, "PandaEar"),
            (241, "HotDogHat"),
            (246, "AP_FloatingCrown"),
            (247, "AP_TeachersPet"),
            (248, "AntelopeHorn"),
            (249, "Headslug"),
            (250, "JohnJuniper"),
        };

        public static List<(int id, string name)> hands = new()
        {
            (127, "No Gloves"),
            (128, "VigilanteGloves"),
            (129, "GamerGlove"),
            (130, "Spy"),
            (131, "NumberOne"),
            (132, "ContainmentHands"),
            (133, "Museum"),
            (134, "ScrubGlub"),
            (135, "CandyCorn"),
            (136, "Ripper"),
            (137, "Vampire"),
            (138, "Werewolf"),
            (139, "Cufflinks"),
            (140, "FingerGloves"),
            (141, "MoonGloves"),
            (142, "RingGloves"),
            (143, "WindowGloves"),
            (144, "CoolBeanGloves"),
            (145, "Jloves"),
            (146, "SidekickGloves"),
            (147, "BeastGloves"),
            (148, "BalloonGloves"),
            (149, "OilGloves"),
            (150, "SpaceGloves"),
            (151, "DeluxeSpaceGloves"),
            (152, "FishEatingFinger"),
            (153, "ShellBracelet"),
            (154, "FrankenBeanHands"),
            (155, "GoldWatch"),
            (156, "SlimeHands"),
            (157, "StickyFingers"),
            (158, "WinterMittens"),
            (159, "FOnesieHands"),
            (160, "TrainConductorHands"),
            (242, "BurgerTime"),
        };

        public static List<(int id, string name)> skins = new()
        {
            (161, "No Skin"),
            (162, "Mechanic"),
            (163, "SuitedUp"),
            (164, "FannyPack"),
            (165, "Sheriff"),
            (166, "BlingSkin"),
            (167, "ChaosContainmentSkin"),
            (168, "HazmatSkin"),
            (169, "ScientistSkin"),
            (170, "SuitedUpWhite"),
            (171, "Jorts"),
            (172, "FrogSuit"),
            (173, "RedDragonSkin"),
            (174, "MooseSkin"),
            (175, "LeftHandMan"),
            (176, "ChefSkin"),
            (177, "MinerSkin"),
            (178, "WinterSkin"),
            (179, "SidekickSkin"),
            (180, "CatTail"),
            (181, "AstronaughtSkin"),
            (182, "PilotSkin"),
            (183, "SpaceBean"),
            (184, "SpaceBeanDeluxe"),
            (185, "SquidSkin"),
            (186, "SwimTrunks"),
            (187, "LifeJacket"),
            (188, "FrankenBeanSkin"),
            (189, "SlimeSkin"),
            (190, "WerewolfSkin"),
            (191, "VictorianSuit"),
            (192, "BatBeanSkin"),
            (193, "LegWarmers"),
            (194, "FOnesieSkin"),
            (195, "TrainConductorSkin"),
            (196, "Tiger"),
            (197, "Fox"),
            (198, "Possum"),
            (199, "LavaRockSkin"),
            (200, "KarateSkin"),
            (201, "Raccoon"),
            (202, "ShroomPants"),
            (203, "RainCoat"),
            (204, "GeodeBody"),
            (205, "Gardener"),
            (206, "GreenFairy"),
            (243, "GreenSweater"),
            (244, "SchoolUniform"),
            (245, "Cat"),
        };

        public static List<string> Usernames = new List<string>
        {
            "PolusPanic232",
            "AirlockClient234",
            "EchoHacker278",
            "GlitchDragon461",
            "NullTrace560",
            "DeepWire72",
            "TurboGhost77",
            "DarkHacker720",
            "ByteRunner716",
            "PizzaWizard970",
            "CyanShade806",
            "DonutJoker811",
            "LofiShade626",
            "NeonRunner57",
            "FrostRunner296",
            "HyperByte810",
            "TurboIRL56",
            "GhostAI741",
            "RetroJoker58",
            "ErrorEater759",
            "OverFlip625",
            "VortexPointer852",
            "NullIRL411",
            "RoleShift342",
            "HexShade625",
            "PixelMode241",
            "ZeroSwapper539",
            "PhasePanic148",
            "NovaNinja684",
            "RoleMode871",
            "NeonSuit115",
            "CrimsonKing79",
            "VentPhantom491",
            "VentEater65",
            "SilentGhost256",
            "NovaShade589",
            "GlitchByte505",
            "StaticMode654",
            "ErrorEater767"
        };
    }
}