using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AirlockClient.Managers
{
    public static class ListsManager
    {
       public static List<(int id, string name)> hats = new()
       {
            (13, "Balloon"),
            (14, "Beanie"),
            (15, "FedoraTrillby"),
            (16, "FloatyFlamingo"),
            (17, "Greh"),
            (18, "Heart"),
            (19, "Mohawk"),
            (20, "Sprout"),
            (21, "Batbean"),
            (22, "Headphones"),
            (23, "Headslug"),
            (24, "MiniCrewmate"),
            (25, "PlagueMask"),
            (26, "Present"),
            (27, "Candycane"),
            (28, "Decorations"),
            (29, "Elf"),
            (30, "Reindeer"),
            (31, "Santa"),
            (32, "Snowman"),
            (33, "Trophy"),
            (34, "Pizzatime"),
            (35, "Banana"),
            (36, "MagicCorn"),
            (37, "Morawk"),
            (38, "Note2Self"),
            (39, "ThirdEye"),
            (40, "Clogged"),
            (41, "ColdBrim"),
            (42, "LavaRock"),
            (43, "MinersSetback"),
            (44, "OSHAComplient"),
            (45, "PHat"),
            (46, "SafetySencond"),
            (47, "Snowmate"),
            (48, "ThisIsNotADrill"),
            (49, "UniqueSpecimen"),
            (50, "Crewhorse"),
            (51, "Bearhug"),
            (52, "GasMask"),
            (53, "PengYinz"),
            (54, "SnowDay"),
            (55, "SnowflakeCrown"),
            (56, "CozyHat"),
            (57, "CozyMuffs"),
            (58, "IceCrewmate"),
            (59, "KittyHoodie"),
            (60, "WhippedCream"),
            (61, "Floatyassaurus"),
            (62, "Hooked"),
            (63, "CrabGrab"),
            (64, "Sandcastle"),
            (65, "Funguy"),
            (66, "BeanusFlytrap"),
            (67, "CapCap"),
            (68, "DishJockey"),
            (69, "MoRocks"),
            (70, "Sandmate"),
            (71, "ShadyBusiness"),
            (72, "Overscoped"),
            (73, "Zomburrito"),
            (74, "Chef"),
            (75, "VigilanteHat"),
            (76, "ContainmentHat"),
            (77, "Janitor"),
            (78, "MopHead"),
            (79, "ChocolateScoop"),
            (80, "LastWipe"),
            (81, "VictoriaHair"),
            (82, "WerewolfHat"),
            (83, "Pumpkin"),
            (84, "Wizard"),
            (85, "TenGallons_Stace"),
            (86, "TenGallons_White"),
            (87, "CashHat"),
            (88, "ChoasContainmentHat"),
            (89, "HazmentMask"),
            (90, "ScientistMask"),
            (91, "TopHatDark"),
            (92, "TopHatWhite"),
            (93, "FrogHat"),
            (94, "RedDragonHat"),
            (95, "RabbitEars"),
            (96, "PinkBow"),
            (97, "MooseHat"),
            (98, "LunarNewYearDragon"),
            (99, "SGOrangeTop"),
            (100, "AstronaughtHat"),
            (101, "PilotHat"),
            (102, "LunarNewYearDog"),
            (103, "NyanCatEars"),
            (104, "SidekickHat"),
            (105, "ScanalyzerHat"),
            (106, "ScanalyzerDeluxeHat"),
            (107, "SquidHat"),
            (108, "GreenFishHat"),
            (109, "MinerHatBrown"),
            (110, "TurtleHat"),
            (111, "HatVR_Black"),
       };

        public static List<(int id, string name)> hands = new()
        {
            (113, "VigilanteGloves"),
            (114, "GamerGlove"),
            (115, "Spy"),
            (116, "NumberOne"),
            (117, "ContainmentHands"),
            (118, "Museum"),
            (119, "ScrubGlub"),
            (120, "CandyCorn"),
            (121, "Ripper"),
            (122, "Vampire"),
            (123, "Werewolf"),
            (124, "Cufflinks"),
            (125, "FingerGloves"),
            (126, "MoonGloves"),
            (127, "RingGLoves"),
            (128, "WindowGloves"),
            (129, "CoolBeanGloves"),
            (130, "Jloves"),
            (131, "SidekickGloves"),
            (132, "BeastGloves"),
            (133, "BalloonGloves"),
            (134, "OilGloves"),
            (135, "SpaceGloves"),
            (136, "DeluxeSpaceGloves"),
            (137, "FishEatingFinger"),
            (138, "ShellBlacelet"),
        };

        public static List<(int id, string name)> skins = new()
        {
            (140, "Mechanic"),
            (141, "SuitedUp"),
            (142, "Fannypack"),
            (143, "Sheriff"),
            (144, "BlingSkin"),
            (145, "ChaosContainmentSkin"),
            (146, "HazmatSkin"),
            (147, "ScientistSkin"),
            (148, "SuitedUpWhite"),
            (149, "Jorts"),
            (150, "FrogSuit"),
            (151, "RedDragonSkin"),
            (152, "MooseSkin"),
            (153, "LeftHandMan"),
            (154, "ChefSkin"),
            (155, "MinerSkin"),
            (156, "WinterSkin"),
            (157, "SidekickSkin"),
            (158, "CatTail"),
            (159, "AstronaughtSkin"),
            (160, "PilotSkin"),
            (161, "SpaceBean"),
            (162, "SpaceBeanDeluxe"),
            (163, "SquidSkin"),
            (164, "SwimTrunks"),
            (165, "LifeJacket"),
        };
        public static List<string> Usernames = new List<string> // had Chatgpt make these was too lazy to do it myself
        {
            "PolusPanic232",
            "AirlockClient234",
            "EchoHacker278",
            "GlitchDragon461",
            "NullTrace560",
            "DeepWire72",
            "TurboGhost77",
            "DarkHacker720",
            "ByteRunner716",
            "PizzaWizard970",
            "CyanShade806",
            "DonutJoker811",
            "LofiShade626",
            "NeonRunner57",
            "FrostRunner296",
            "HyperByte810",
            "TurboIRL56",
            "GhostAI741",
            "RetroJoker58",
            "ErrorEater759",
            "OverFlip625",
            "VortexPointer852",
            "NullIRL411",
            "RoleShift342",
            "HexShade625",
            "PixelMode241",
            "ZeroSwapper539",
            "PhasePanic148",
            "NovaNinja684",
            "RoleMode871",
            "NeonSuit115",
            "CrimsonKing79",
            "VentPhantom491",
            "VentEater65",
            "SilentGhost256",
            "NovaShade589",
            "GlitchByte505",
            "StaticMode654",
            "ErrorEater767"
        };
    }
}
